---
title: A Larger World
weight: 8
bookToc: false
---

```{r setup, include=FALSE}
source('../../../setup.R')
```

# A Larger World {#sec:conclusion}

There is more to learn about plain text, and this book just gets you started but hopefully it has given you a substantial command over the most important tools for adopting plain text software for your research and writing. It is as good a moment as any to reiterate that plain text isn't for everyone; it presents complications to your work that some find to be excessive. Fiddling with the settings of your computer or installing esoteric software and establishing the appropriate workflow for working with these tools can seem to some scholars like a bridge too far, and so they settle for using Word and Google Docs, endlessly copying and pasting figures and tables into their documents and remembering the citation conventions in their fields. That is all well and good but learning plain text for authoring papers is only the beginning of what we can use plain text tools for in communicating our scientific findings. This larger world of plaintext tools is vast but I think there are a few next places you should visit.

Now that you have an understanding of the conventions of markup languages including LaTeX, markdown and Rmarkdown, you can take advantage your new found skills to go in any number of different directions to communicate your work to a wide audience. You can start by authoring your own websites. [Hugo](https://gohugo.io/) is a static site generator that allows you to use markdown files to create websites without having an extensive understanding of HTML. Hugo offers customizable templates that have been created for a variety of purposes, that are both beautiful and simple to use. You can even go one step further and use Rmarkdown and the [`blogdown`](https://github.com/rstudio/blogdown) package to use dynamic documents to create websites. This will be particularly helpful when authoring documentation for packages you write or for providing resources for reproducing your work to a wide audience. I have used both extensively to create a number of websites including my personal site, [timothyelder.com](https://timothyelder.com) as well as a site for this book, [introtoplaintext.com](https://introtoplaintext.com). Using Hugo you can [host your website on GitHub](https://pages.github.com/) using a custom domain purchased from domain registrars like GoDaddy, Squarespace, or DreamHost.

You could also write your own book using the [`bookdown`](https://bookdown.org/) package, or develop web apps using R [`shiny`](https://shiny.posit.co/). Whatever you decide to do, you'll be sure to find lots of resources to get you started. One of the advantages of using open source software that we have outlined here is that not only is everything free to use but there are also large user bases that collectively contribute to knowledge-bases. You'll find lots of help with most of your questions on [StackOverflow](https://stackoverflow.com/) and the packages that have been outlined here all have excellent documentation. For further reading you might begin with some of the books below.

### Suggested Reading

<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry" style="margin-bottom: 1em;">Christensen, Garret S., Jeremy Freese, and Edward Miguel. 2019. <i>Transparent and Reproducible Social Science Research: How to Do Open Science</i>. Oakland, California: University of California Press.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-0-520-29693-0%20978-0-520-29695-4&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Transparent%20and%20reproducible%20social%20science%20research%3A%20how%20to%20do%20open%20science&amp;rft.place=Oakland%2C%20California&amp;rft.publisher=University%20of%20California%20Press&amp;rft.aufirst=Garret%20S.&amp;rft.aulast=Christensen&amp;rft.au=Garret%20S.%20Christensen&amp;rft.au=Jeremy%20Freese&amp;rft.au=Edward%20Miguel&amp;rft.date=2019&amp;rft.tpages=249&amp;rft.isbn=978-0-520-29693-0%20978-0-520-29695-4"></span>
  <div class="csl-entry" style="margin-bottom: 1em;">Healy, Kieran. 2018. <i>Data Visualization: A Practical Introduction</i>. Princeton, NJ: Princeton University Press.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-0-691-18161-5%20978-0-691-18162-2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=Data%20visualization%3A%20a%20practical%20introduction&amp;rft.place=Princeton%2C%20NJ&amp;rft.publisher=Princeton%20University%20Press&amp;rft.aufirst=Kieran&amp;rft.aulast=Healy&amp;rft.au=Kieran%20Healy&amp;rft.date=2018&amp;rft.isbn=978-0-691-18161-5%20978-0-691-18162-2"></span>
  <div class="csl-entry" style="margin-bottom: 1em;">Kottwitz, Stefan. 2015. <i>LaTeX Cookbook : Over 90 Hands-on Recipes for Quickly Preparing LaTeX Documents to Solve Various Challenging Tasks</i>. Birmingham, UK: Packt Publishing.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=LaTeX%20cookbook%20%3A%20over%2090%20hands-on%20recipes%20for%20quickly%20preparing%20LaTeX%20documents%20to%20solve%20various%20challenging%20tasks&amp;rft.place=Birmingham%2C%20UK&amp;rft.publisher=Packt%20Publishing&amp;rft.series=Quick%20answers%20to%20common%20problems.&amp;rft.aufirst=Stefan&amp;rft.aulast=Kottwitz&amp;rft.au=Stefan%20Kottwitz&amp;rft.date=2015"></span>
  <div class="csl-entry">Xie, Yihui, Joseph J. Allaire, and Garrett Grolemund. 2019. <i>R Markdown: The Definitive Guide</i>. Boca Raton London New York: CRC Press, Taylor &amp; Francis Group.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=urn%3Aisbn%3A978-1-138-35933-8%20978-1-138-35942-0&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=book&amp;rft.btitle=R%20Markdown%3A%20the%20definitive%20guide&amp;rft.place=Boca%20Raton%20London%20New%20York&amp;rft.publisher=CRC%20Press%2C%20Taylor%20%26%20Francis%20Group&amp;rft.series=Chapman%20%26%20Hall%2FCRC%2C%20the%20R%20series&amp;rft.aufirst=Yihui&amp;rft.aulast=Xie&amp;rft.au=Yihui%20Xie&amp;rft.au=Joseph%20J.%20Allaire&amp;rft.au=Garrett%20Grolemund&amp;rft.date=2019&amp;rft.tpages=303&amp;rft.isbn=978-1-138-35933-8%20978-1-138-35942-0&amp;rft.language=eng"></span>
</div><br>

<div style="text-align: left;">
{{< button relref="chapter-7" >}}Previous{{< /button >}}
</div>